### ISSUE TITLE
Enabling Location Services

### ISSUE THREAD

**Issue by vineetsingh13** [LegendSumeet/eventapp#20]
Pull Request
#issue20

Fixes #(issue number)

Description: Currently the project has no support for location services. This issue proposes the integration of location services to address this gap.

Proposed Solution:
To implement location services, we can use the geocoding and geolocator packages to get the coordinates and name of the locality in the app

**Comment by vineetsingh13** [comment]
@LegendSumeet can you assign this issue to me?

**Comment by praptisharma28** [comment]
Assign me @LegendSumeet under iwoc
