### ISSUE TITLE
[Feature]: Add the github action workflow for greeting contributors 

### ISSUE THREAD

**Issue by praptisharma28** [LegendSumeet/eventapp#25]
Description: 
The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

Proposed Changes:
Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

**Comment by praptisharma28** [comment]
Please assign me this @LegendSumeet under iwoc24

**Comment by LegendSumeet** [comment]
go for it

**Comment by praptisharma28** [comment]
Hey @LegendSumeet please add the difficulty level before assigning.  Coz when a PR comes even we as contributir tend to forget about that tag. Also there are no workflows added in your repo & I need to add them from scratch. I will add for Pull request, bug etc. Do give the level tag as per that. I think I need to add around 5-6 files.
