### ISSUE TITLE
[Feature] Readme Restructuring

### ISSUE THREAD

**Issue by Manishak798** [LegendSumeet/eventapp#28]
### Describe the feature you'd like to request

An Appealing Readme will enhance the overall overview of the project that is currently missing in your project readme.

### Describe the solution you'd like

Restructuring the whole readme file with details about the project will help your project to be more understandable to the contributors. I am a SWOC'24 Mentor raising this issue for contributors to contribute.

**Comment by Manishak798** [comment]
Hey @LegendSumeet as I mentioned I am SWOC Mentor and not a contributor I raised this issue for contributors to contribute in your project and If you agree I am happy to be a mentor for this project.

**Comment by LegendSumeet** [comment]
@Manishak798 okay thanks 😊

**Comment by Manishak798** [comment]
> @Manishak798 okay thanks 😊

You're welcome!

**Comment by vijaymehrotra** [comment]
Can i contribute to this project..
