### ISSUE TITLE
[Feature]: Add the pr-title-checker.yml and it's json for keeping tracks of PR.

### ISSUE THREAD

**Issue by praptisharma28** [LegendSumeet/eventapp#29]
### Describe the feature you'd like to request

This will :
/Improved Code Organization: Consistent PR titles will enhance code organization and searchability.
/Streamlined Workflow: Integration with CodeQL and a dedicated workflow will promote efficiency and automation.
/Reduced Manual Effort: Automated checks will minimize the need for manual title review, freeing up time for development tasks.

### Describe the solution you'd like

Help to future contributors

**Comment by praptisharma28** [comment]
Assign me @LegendSumeet under iwoc

**Comment by LegendSumeet** [comment]
Your SWOC CONTRIBUTOR

**Comment by praptisharma28** [comment]
> Your SWOC CONTRIBUTOR

I am IWOC contributor, please dd that tag along with difficulty level thanks.

**Comment by praptisharma28** [comment]
@LegendSumeet tags?

**Comment by praptisharma28** [comment]
> > Your SWOC CONTRIBUTOR
> 
> I am IWOC contributor, please dd that tag along with difficulty level thanks.

@LegendSumeet please follow the guidelines, I asked before too. Thankyou!
