### ISSUE TITLE
Improve UI of HomePage 

### ISSUE THREAD

**Issue by LegendSumeet** [LegendSumeet/eventapp#7]

**Comment by WhyC03** [comment]
Hello @LegendSumeet ,
I am interested in contributing to this feature.
Can you please share some ideas on what improvements are required?

**Comment by harshydv99** [comment]
Hey @LegendSumeet 

I would love to work upon this and would give my best to provide you with an efficient and easy to interact UI.

Do lemme know what updations you want and it'll be a piece of cake!

Best Regards,
**Shera Bhai**

**Comment by Antrimo** [comment]
Hey @LegendSumeet 
I can perform the task, please assign this issue #7 to me.

**Comment by mahesh-bora** [comment]
Hello there! I am interested to contribute to this issue. Can your please assign this issue to me? And also pls let me know if any specific desired changes are to be done.

**Comment by Antrimo** [comment]
Hey @LegendSumeet 
I can perform the task, please assign this issue #7 to me.

**Comment by praptisharma28** [comment]
Assign me this @LegendSumeet under iwoc24

**Comment by praptisharma28** [comment]
@LegendSumeet please add the difficulty level , I am giving the PR.

**Comment by praptisharma28** [comment]
hey @LegendSumeet please give the difficulty tag, its now showing on my dashboard. 

> @LegendSumeet please add the difficulty level , I am giving the PR. I asked before too.
